language: node_js

cache:
  yarn: true

node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'

before_install:
  - npm i -g yarn
  - yarn
  - lerna bootstrap

script:
  - npm test

after_success:
  - npm run coverage:combined
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
