git:
  depth: 10

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '8'


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g pm2

before_script:
  - pm2 start packages/zmarkdown/server/index.js -i 3

after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
