git:
  depth: 10

language: node_js

cache:
  directories:
  - node_modules

node_js:
  - '8'
  - '7'
  - '6'

before_install:
  - npm i -g npm@5
  - lerna bootstrap --hoist

script:
  - npm test

after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
