git:
  depth: 10

language: node_js

cache:
  yarn: true
  directories:
  - node_modules

node_js:
  - '7'
  - '6'

before_install:
  - npm i -g yarn
  - yarn
  - lerna bootstrap

script:
  - npm test

after_success:
  - npm run coverage:combined
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
