git:
  depth: 10

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '10'

env:
  matrix:
    - DEST=/tmp
  global:
    secure: NA4sxCBxsNmOmnZG4HVPKJxeFpcsurt9l0EF6z2Vf6pInCTvaXJ+EdC5m1BdmWAp2ta6A4PSZh0NO1X5bdWfIGYHYD13fu77V6ZglkZ1LNsaTxhWLuXJ7BJta/hZWdT9u8zYGihCBo7Q2MXi3dbdhHbyrb/C2/1nBnTy68wPdtx73yXTHd+n7MGe9N8/4crwOZlVIiGZt2RwlCThcQxl3L6atNWg0UHFTZbOsuGeeMEF/F+nILLDo4gv85jeQ8TRb5AYn/DyggZAOkMcwCnp8gcQBrZxFpY5SIfsKTG1h3Tw3Kr9w537MWgXf9bwZeB+PfEhWKVG11ARwcryJc4Oat4tqsiBfBACIaNQFjbc+h68XM91N0FK4CAnautubU9TjUdkMV2mqbSUh8CB+epDS/1B8G/1f22QvcWLxtdDp/oSGUm2byBvqIdMxRImjzUyzHi6rJ6DDqIMMaa6ztjJS2KG+VLXY2ncSXOOSzdZPOkhD0ggM2Mz3yGePAqe0LNosRRvb/PNRFkeW+wtZbLSDuIOFuPOzORVAmjlaCKM1320zuY6qOhVbrdX6CzXCC/4Wfeyuy/9iRVhDm/m6iSqgyBQv/Nd/utIMk2mQAKhzR25Bi9e9UBGCA/ydViFLT0jrspS/R2ImrC2sS50OujEwcNwQGFW8rY9GJj4FKKK8ks=

before_install:
  - npm install -g pm2

install:
  - npm run bootstrap

before_script:
  - pm2 ping

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build-demo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  target-branch: gh-pages
  local-dir: ./packages/zmarkdown/public
  on:
    branch: master
